[template]
src   = "config.yml"
dest  = "/docker-registry/config/config.yml"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "/deis/cache",
  "/deis/registry"
]
check_cmd = "/app/bin/check {{ .src }}"
reload_cmd = "/app/bin/reload"
